### ISSUE TITLE
name resolution test cases

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#21]
New rust-analyzer name resolution module just landed! 🎉  Thanks to @lzoghbi for the hard work!!

It works in most cases. This thread for a few rarer bugs/issues with it to be resolved.

The plan is to soon 🔥 🗑️ deprecate and delete 🗑️ 🔥 the old resolution code, currently in `hacky_resolution.rs` -- in the interim, I will use `hacky_resolution` as a fallback for the rare cases when the new resolver fails.

**Comment by cdstanford** [comment]
Here's one of the test cases that is failing in `toy_crates`. It may be that name resolution ignores platform-specific code (this is Linux code), that may be the source of the issue

```
% cargo run --release --bin check_resolution data/test-packages/toy-crates 42 8 get_num_physical_cpus -f src/num_cpus.rs
   Compiling cargo-scan v0.1.0 (/Users/caleb/git/research/RustSec/cargo-scan)
    Finished release [optimized] target(s) in 4.53s
     Running `target/release/check_resolution data/test-packages/toy-crates 42 8 get_num_physical_cpus -f src/num_cpus.rs`
Could not classify token IDENT@864..885 "get_num_physical_cpus"
```

**Comment by cdstanford** [comment]
It would be great to add some additional moderately complex test cases for method resolution, like `String::new().clone() + "hello" + " " + "world"`

See `scanner::lookup_method` for how we are currently handling these (ignoring them)

Also test cases for a struct with a function field -- see `scanner::lookup_field` and `scanner::lookup_field_index`

**Comment by cdstanford** [comment]
Another odd crash when running on the `rand` crate:

```
thread 'main' panicked at '

Failed to lookup FN@5715..7067 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..21845
known nodes: SOURCE_FILE@0..21845

', /Users/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir-0.0.149/src/semantics.rs:1371:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Run `make top10` to replicate -- or run cargo scan directly on `data/packages/rand`

**Comment by cdstanford** [comment]
I think this is the same crash on `syn`:

```
% ./scripts/scan.py -c syn     
INFO:root:=== Scanning syn in data/packages ===
thread 'main' panicked at '

Failed to lookup FN@5715..7067 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..21845
known nodes: SOURCE_FILE@0..21845

', /Users/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir-0.0.149/src/semantics.rs:1371:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cdstanford** [comment]
Here's a backtrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: ra_ap_hir::semantics::SemanticsImpl::find_file::{{closure}}
   3: ra_ap_hir::semantics::SemanticsImpl::find_file
   4: cargo_scan::name_resolution::Resolver::get_container_name::{{closure}}::{{closure}}
   5: cargo_scan::name_resolution::Resolver::get_container_name
   6: cargo_scan::name_resolution::Resolver::resolve_ident
   7: cargo_scan::resolve::FileResolver::resolve_core
   8: <cargo_scan::resolve::FileResolver as cargo_scan::resolve::Resolve>::resolve_path
   9: cargo_scan::scanner::Scanner::scan_expr
  10: cargo_scan::scanner::Scanner::scan_expr
  11: cargo_scan::scanner::Scanner::scan_expr
  12: cargo_scan::scanner::Scanner::scan_expr
  13: cargo_scan::scanner::Scanner::scan_expr
  14: cargo_scan::scanner::Scanner::scan_expr
  15: cargo_scan::scanner::Scanner::scan_expr
  16: cargo_scan::scanner::Scanner::scan_fn
  17: cargo_scan::scanner::Scanner::scan_item
  18: cargo_scan::scanner::load_and_scan
  19: cargo_scan::scanner::scan_crate
  20: scan::main
```

**Comment by cdstanford** [comment]
These are all resolved except the platform-specific stuff that we will discuss separately. Closing, thanks!!
