### ISSUE TITLE
Name resolution panics on hashbrown

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#25]
I'm getting another interesting error on the `hashbrown` crate:

```
% RUST_LOG=info ./scripts/scan.py -c hashbrown
INFO:root:=== Scanning hashbrown in data/packages ===
[2023-04-25T00:31:56Z INFO  cargo_scan::scanner] Scanning crate: "data/packages/hashbrown"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/name_resolution.rs:391:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks possibly different than the errors from before

**Comment by cdstanford** [comment]
This error also occurs on `tinyvec`

```
[2023-04-25T20:04:24Z INFO  cargo_scan::scanner] Scanning crate: "data/packages/tinyvec"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/name_resolution.rs:391:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cdstanford** [comment]
Probably we should fix this in the short term by adding more `Result<()>` types throughout the `name_resolution.rs` return types so we can use `?` instead of unwrap.

**Comment by cdstanford** [comment]
resolved! 🎉
