### ISSUE TITLE
assertion failures at `src/effect.rs:218:13`

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#27]
another one for me to come back to

```
[2023-04-25T20:06:49Z INFO  cargo_scan::scanner] Scanning crate: "data/packages/uuid"
thread 'main' panicked at 'assertion failed: is_unsafe', src/effect.rs:218:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cdstanford** [comment]
```
[2023-04-25T20:05:01Z INFO  cargo_scan::scanner] Scanning crate: "data/packages/instant"
thread 'main' panicked at 'assertion failed: is_unsafe', src/effect.rs:218:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cdstanford** [comment]
```
[2023-04-25T20:12:25Z INFO  cargo_scan::scanner] Scanning crate: "data/packages/reqwest"
thread 'main' panicked at 'assertion failed: is_unsafe', src/effect.rs:218:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cdstanford** [comment]
```
[2023-04-25T20:24:17Z INFO  cargo_scan::scanner] Scanning crate: "data/packages/js-sys"
thread 'main' panicked at 'assertion failed: is_unsafe', src/effect.rs:218:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
