### ISSUE TITLE
Type resolution crash on `proc_macro2`

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#31]
```thread 'main' panicked at 'Definition should have a type', src/name_resolution.rs:456:6```

backtrace:

```
./scripts/scan.py -c proc-macro2
INFO:root:=== Scanning proc-macro2 in data/packages ===
thread 'main' panicked at 'Definition should have a type', src/name_resolution.rs:456:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
INFO:root:=== Results ===
INFO:root:===== All results =====

INFO:root:===== Crate Summary =====
Number of dangerous imports by crate:
===== Crate Totals =====
0 crates with 1 or more dangerous imports
1 crates with 0 dangerous imports

caleb@caleb-mac cargo-scan % RUST_BACKTRACE=1 ./scripts/scan.py -c proc-macro2
INFO:root:=== Scanning proc-macro2 in data/packages ===
thread 'main' panicked at 'Definition should have a type', src/name_resolution.rs:456:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/option.rs:1924:5
   5: core::option::Option<T>::expect
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/option.rs:786:21
   6: cargo_scan::name_resolution::get_canonical_type
             at ./src/name_resolution.rs:436:14
   7: cargo_scan::name_resolution::Resolver::resolve_type
             at ./src/name_resolution.rs:188:9
   8: cargo_scan::resolve::FileResolver::resolve_type_core
             at ./src/resolve.rs:88:9
   9: cargo_scan::resolve::FileResolver::resolve_type_or_else
             at ./src/resolve.rs:111:15
  10: <cargo_scan::resolve::FileResolver as cargo_scan::resolve::Resolve>::resolve_field_type
             at ./src/resolve.rs:188:9
  11: cargo_scan::scanner::Scanner::scan_deref::{{closure}}
             at ./src/scanner.rs:560:26
  12: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/iter/traits/iterator.rs:834:29
  13: core::iter::traits::iterator::Iterator::fold
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/iter/traits/iterator.rs:2438:21
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/iter/traits/iterator.rs:837:9
  15: cargo_scan::scanner::Scanner::scan_deref
             at ./src/scanner.rs:558:9
  16: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:528:21
  17: cargo_scan::scanner::Scanner::scan_expr_call_args
             at ./src/scanner.rs:596:13
  18: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:474:17
  19: cargo_scan::scanner::Scanner::scan_fn_local
             at ./src/scanner.rs:360:13
  20: cargo_scan::scanner::Scanner::scan_fn_statement
             at ./src/scanner.rs:344:36
  21: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:397:21
  22: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:420:17
  23: cargo_scan::scanner::Scanner::scan_expr_call_args
             at ./src/scanner.rs:596:13
  24: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:474:17
  25: cargo_scan::scanner::Scanner::scan_fn_statement
             at ./src/scanner.rs:345:42
  26: cargo_scan::scanner::Scanner::scan_fn
             at ./src/scanner.rs:327:13
  27: cargo_scan::scanner::Scanner::scan_method
             at ./src/scanner.rs:290:9
  28: cargo_scan::scanner::Scanner::scan_impl
             at ./src/scanner.rs:257:21
  29: cargo_scan::scanner::Scanner::scan_item
             at ./src/scanner.rs:174:37
  30: cargo_scan::scanner::Scanner::scan_file
             at ./src/scanner.rs:164:13
  31: cargo_scan::scanner::scan_file
             at ./src/scanner.rs:727:5
  32: cargo_scan::scanner::try_scan_file
             at ./src/scanner.rs:740:5
  33: cargo_scan::scanner::scan_crate_with_sinks
             at ./src/scanner.rs:776:13
  34: cargo_scan::scanner::scan_crate
             at ./src/scanner.rs:809:5
  35: scan::main
             at ./src/bin/scan.rs:29:19
  36: core::ops::function::FnOnce::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
INFO:root:=== Results ===
INFO:root:===== All results =====

INFO:root:===== Crate Summary =====
Number of dangerous imports by crate:
===== Crate Totals =====
0 crates with 1 or more dangerous imports
1 crates with 0 dangerous imports
```

**Comment by cdstanford** [comment]
fixed by @lzoghbi , thanks!
