### ISSUE TITLE
name resolution crash on `serde_json`

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#33]
Another name resolution crash, I think different from before:
```
% RUST_BACKTRACE=1 cargo run --bin scan data/packages/serde_json
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s
     Running `target/debug/scan data/packages/serde_json`
[2023-05-31T20:17:38Z WARN  cargo_scan::scanner] Failed to scan file: data/packages/serde_json/src/features_check/error.rs (expected one of: `fn`, `extern`, `use`, `static`, `const`, `unsafe`, `mod`, `type`, `struct`, `enum`, `union`, `trait`, `auto`, `impl`, `default`, `macro`, identifier, `self`, `super`, `crate`, `::`)
thread 'main' panicked at '

Failed to lookup LITERAL@11448..11449 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..50457
known nodes: SOURCE_FILE@0..26269
```

backtrace:
```
', /Users/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir-0.0.149/src/semantics.rs:1371:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: ra_ap_hir::semantics::SemanticsImpl::find_file::{{closure}}
   3: ra_ap_hir::semantics::SemanticsImpl::find_file
   4: ra_ap_hir::semantics::SemanticsImpl::analyze_impl
   5: ra_ap_hir::semantics::SemanticsImpl::type_of_expr
   6: ra_ap_hir::semantics::Semantics<DB>::type_of_expr
             at /Users/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir-0.0.149/src/semantics.rs:345:9
   7: cargo_scan::name_resolution::get_canonical_type::{{closure}}
             at ./src/name_resolution.rs:493:30
   8: core::option::Option<T>::and_then
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/option.rs:1309:24
   9: cargo_scan::name_resolution::get_canonical_type
             at ./src/name_resolution.rs:491:36
  10: cargo_scan::name_resolution::Resolver::resolve_type
             at ./src/name_resolution.rs:192:9
  11: cargo_scan::resolve::FileResolver::resolve_type_core
             at ./src/resolve.rs:118:9
  12: cargo_scan::resolve::FileResolver::resolve_type_or_else::{{closure}}
             at ./src/resolve.rs:147:36
  13: cargo_scan::resolve::FileResolver::resolve_or_else
             at ./src/resolve.rs:127:9
  14: cargo_scan::resolve::FileResolver::resolve_type_or_else
             at ./src/resolve.rs:147:9
  15: <cargo_scan::resolve::FileResolver as cargo_scan::resolve::Resolve>::resolve_path_type
             at ./src/resolve.rs:167:9
  16: cargo_scan::scanner::Scanner::scan_path
             at ./src/scanner.rs:590:18
  17: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:516:17
  18: cargo_scan::scanner::Scanner::scan_fn_statement
             at ./src/scanner.rs:375:42
  19: cargo_scan::scanner::Scanner::scan_expr
             at ./src/scanner.rs:471:21
  20: cargo_scan::scanner::Scanner::scan_fn_statement
             at ./src/scanner.rs:375:42
  21: cargo_scan::scanner::Scanner::scan_fn
             at ./src/scanner.rs:357:13
  22: cargo_scan::scanner::Scanner::scan_fn_decl
             at ./src/scanner.rs:315:9
  23: cargo_scan::scanner::Scanner::scan_item
             at ./src/scanner.rs:185:35
  24: cargo_scan::scanner::Scanner::scan_mod
             at ./src/scanner.rs:204:17
  25: cargo_scan::scanner::Scanner::scan_item
             at ./src/scanner.rs:180:34
  26: cargo_scan::scanner::Scanner::scan_file
             at ./src/scanner.rs:174:13
  27: cargo_scan::scanner::scan_file
             at ./src/scanner.rs:829:5
  28: cargo_scan::scanner::try_scan_file
             at ./src/scanner.rs:842:5
  29: cargo_scan::scanner::scan_crate_with_sinks
             at ./src/scanner.rs:878:13
  30: cargo_scan::scanner::scan_crate
             at ./src/scanner.rs:911:5
  31: scan::main
             at ./src/bin/scan.rs:29:19
  32: core::ops::function::FnOnce::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Similar error to #21 but those are now fixed, I wonder if a similar fix can be applied here?

Same crate as #26, but different error

There's no `.unwrap()` in the line in question so I am not sure exactly how to suppress and report the error.

**Comment by cdstanford** [comment]
Resolved! Thanks @lzoghbi !
